### ISSUE TITLE
does not play nice with install_github

### ISSUE THREAD

**Issue by jennybc** [timelyportfolio/gitgraphR#2]
Rest assured, I will install this another way.

But some combination of the forking, branching, non-master default branch, and use of a subdirectory makes this hard to install with `devtools::install_github`. And I think it's at the GitHub / API level. The usual zipball links 404 and I have no idea why. Example:

https://api.github.com/repos/timelyportolio/gitgraphr/zipball/master

**Comment by timelyportfolio** [comment]
Ok, I will fix it up to standard tonight.  I was trying to preserve history from gitgraph.js but I guess this was a bad idea.

**Comment by timelyportfolio** [comment]
@jennybc, this should play nicely now.  Please let me know.  Sorry for the trouble.

**Comment by timelyportfolio** [comment]
![image](https://cloud.githubusercontent.com/assets/837910/17953738/8cb0003a-6a3b-11e6-9825-65973e9bc260.png)

**Comment by jennybc** [comment]
What was it? Disregard if I won't learn anything from this. I'm just curious what aspect of the set up broke the zipball thing. I've never seen that before.

**Comment by timelyportfolio** [comment]
Sorry, I misunderstood.  I am not sure what was causing the tarball issue.  I will explain the very basic and little that I know.

I did two things that made `devtools::install_github` difficult.

### subdirectory for the R package

I put the R package in a subdirectory `pkg`.  This requires using the `subdir` argument of `devtools::install_github`.  If this were the only difficulty I introducted, we could install with:

```
devtools::install_github("timelyportfolio/gitgraphR", subdir="pkg")
```

### non-`master` branch

In addition, I put the R package in a branch `R` which is not `master`.  _On Github, I set the default branch to be `R`, but I have no idea what that might mess up._  To install with a different branch, we can do

```
devtools::install_github("timelyportfolio/gitgraphR@R")
```

### installing with subdir and non-master branch

With the two complexities introduced, we then have to do the very ugly

```
devtools::install_github("timelyportfolio/gitgraphR@R", subdir="pkg")
```

**Comment by jennybc** [comment]
Yeah I couldn't find any other R package repos that had all of these wrinkles going on at the same time. But I actually created a test repo and fiddled with default branch and it didn't seem to mess up the zipball access. Which appeared to be the problem. Not anything deeper in devtools. I guess this will just remain a mystery.
